### ISSUE TITLE
Changement de nom dans Domoticz

### ISSUE THREAD

**Issue by Mat2Vence** [landaisbenj/jarvis-domoticz#5]
En cas de mise à jour de nom d'appareil dans domoticz post installation du plugin dans Jarvis, le nouveau nom n'est pas pris en compte. Existe-t-il un moyen simple (sans désinstaller) de faire en sorte que les modifications soient prises en compte?

**Comment by Oeil2L** [comment]
Essaye de désactiver et réactiver le plugin dans Jarvis.

Lorsque je passe un nouveau device en favoris, cette manip suffisait à connaitre le nouveau device.

**Comment by landaisbenj** [comment]
La liste des noms n'est pas connu de jarvis. Elle est recuperé en direct lorsque du lance une commande. Du coup il n'y a normalement pas de raison que jarvis se trompe. Si c'est le cas c'est surement domoticz qui ne fournis pas le bon nom.
Il faut verifier dans ce cas avec l'api json pour voir ce qu'il ressort.
