### ISSUE TITLE
Domoticz  https

### ISSUE THREAD

**Issue by babas89** [landaisbenj/jarvis-domoticz#6]
Bonjour,
Je rencontre un probleme avec le plugin.
Quand j'ai installé Domoticz, je n'ai pas activé l'acces http seulement le https.
Quand j'ai configuré le plugin, j'ai noté l'adresse IP de domoticz xxx.xxx.xxx.xxx et le port 443.
J'ai essayé le plugin mais il ne fonctionne pas.
Je pense avoir compris le probleme, dans le fichier functions.sh la ligne de commande est la suivante
"http://${pg_dz_domoticz_ip}:${pg_dz_domoticz_port}"
Si sur un PC je tape l'adresse http://xxx.xxx.xxx.xxx:443 dans un navigateur je n'arrive pas sur Domoticz 
il faut que je tape https://xxx.xxx.xxx.xxx

**Comment by landaisbenj** [comment]
J'ai rajouter le http dans la config. Il faut juste le modifier en https. Je pense que cela devrait etre suffisant. Si tu peux modifier et faire un retour ce serai cool merci :)

**Comment by babas89** [comment]
Merci pour ton retour, j'ai désinstallé mon installation et donc je ne peux plus tester.
Bonne journée
